name: ppb_progress
description: "Ini adalah project khusus untuk tugas PPB XII"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.5.0
  cloud_firestore: 4.14.0
  firebase_storage: ^11.1.0
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/img/robo_nobg.png
