// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkDMpOYy3NFzah4IV1n4aE6Nmsb3EUsyI',
    appId: '1:52305321188:web:c07cf631a745ebea7460f1',
    messagingSenderId: '52305321188',
    projectId: 'learningflutter-781a7',
    authDomain: 'learningflutter-781a7.firebaseapp.com',
    storageBucket: 'learningflutter-781a7.appspot.com',
    measurementId: 'G-1LK80TJ65C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3UeL-byojB-qoXD9jTjQuuvScwku6Xtg',
    appId: '1:52305321188:android:04c0cffaf8e60c117460f1',
    messagingSenderId: '52305321188',
    projectId: 'learningflutter-781a7',
    storageBucket: 'learningflutter-781a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKxvV7abQQo4nYIAhmi3qroPrN4yBimA4',
    appId: '1:52305321188:ios:55186be05fa09d1b7460f1',
    messagingSenderId: '52305321188',
    projectId: 'learningflutter-781a7',
    storageBucket: 'learningflutter-781a7.appspot.com',
    iosBundleId: 'com.example.ppbProgress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKxvV7abQQo4nYIAhmi3qroPrN4yBimA4',
    appId: '1:52305321188:ios:55186be05fa09d1b7460f1',
    messagingSenderId: '52305321188',
    projectId: 'learningflutter-781a7',
    storageBucket: 'learningflutter-781a7.appspot.com',
    iosBundleId: 'com.example.ppbProgress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkDMpOYy3NFzah4IV1n4aE6Nmsb3EUsyI',
    appId: '1:52305321188:web:82ea32999dd68fbd7460f1',
    messagingSenderId: '52305321188',
    projectId: 'learningflutter-781a7',
    authDomain: 'learningflutter-781a7.firebaseapp.com',
    storageBucket: 'learningflutter-781a7.appspot.com',
    measurementId: 'G-MFLHFPQD4Q',
  );
}
